export type SVG_ICONS_TYPE = 
        'activity'
    |   'arrow'
    |   'calendar'
    |   'chat'
    |   'check'
    |   'checked'
    |   'close'
    |   'delete'
    |   'edit'
    |   'eye_off'
    |   'eye'
    |   'home'
    |   'link'
    |   'logo'
    |   'logout'
    |   'notification'
    |   'option'
    |   'plus'
    |   'profile'
    |   'setting'
    |   'settings'
    |   'team'
    |   'error'